### ISSUE TITLE
[Feature Request] Additional /hht options (Include Zone Name, add manual flags)

### ISSUE THREAD

**Issue by ZohiDev** [img02/HuntHelper#34]
Hi! I had 2 ideas that I think would add a lot of QoL to the /hht window:

- Add an option in /hht settings to display the A Rank's Zone in the hht window. It'd help speed up re-ordering the flags and also give you an idea of where you're going next
- Add an option in /hht that'd let you manually add a flag. This would help add Starting locations, pit stops etc.

Thanks for your work! Very big fan of HuntHelper :)

**Comment by img02** [comment]
Hey, sorry it's taken a bit. I've added an option for displaying map name in the hunt train.
I'll probably release the new version next week, still working on some other stuff.

I recently added an option for getting the flag for the nearest Aetheryte instead of the next hunts flag, using the command /hhna -- there are also settings for automatic teleport under settings->teleport.

So I won't be adding manual flags at this moment. It's a bit finicky with the current way things are done.
