### ISSUE TITLE
[Feature Under Construction] Seperate the display of spawn points of rank a&b&s

### ISSUE THREAD

**Issue by KirisameVanilla** [img02/HuntHelper#60]
As there are some spawn points for only Rank B or Rank S, is there a posibility to make a ONLY-RANK combo to switch the map images to only rank a spawn points image?

**Comment by img02** [comment]
It's possible but I think difficult because I didn't plan well when I started this project.

I think it would need a lot of little changes, like adding something like
```
 A : true, B : false, S : true 
```

to every single spawn point data : https://github.com/img02/HuntHelper/blob/main/HuntHelper/Data/SpawnPointData.json

and maybe making new map images, etc.

and it would only hide 1-2 B rank spots on some maps.

So maybe in the future, but I don't have much time for it right now.

**Comment by KirisameVanilla** [comment]
i have several ideas, and ill try to do it

i think there are only 3 kinds of need to use HHT

- killing rank a and b to find rank s spawn points
- find rank a points for a hunt train
- spawn those rank s with a need of position e.g. Labyrinthos

for example, if i choose the combo "Killing a and b mode", 
![image](https://github.com/user-attachments/assets/506d8990-7614-444d-ad2e-1cbdc2d15cfd)
then if this pos is not for a and b, skip drawing this pos

**Comment by KirisameVanilla** [comment]
maybe i have time to try to implement this feat, but idk how to make those map images yet. i just sent a message to u(img#7855) via discord. TY ^^
